### ISSUE TITLE
not int, instead String

### ISSUE THREAD

**Issue by hzendejas** [pledbrook/practical-groovy-public#2]
int[] words = new int[] { "orange", "sit", "test", "flabbergasted", "honorific" }

I think it should be:
String[] words = new String[] { "orange", "sit", "test", "flabbergasted", "honorific" }

Any way, in groovy this does not work.

**Comment by pledbrook** [comment]
Oops, yes. Thanks. And yes, the point is to show that that syntax does not work in Groovy as Java developers may expect it to.

**Comment by pledbrook** [comment]
This has been fixed in the source.
