### ISSUE TITLE
Link to Groovy JDK documentation is broken...

### ISSUE THREAD

**Issue by scrain** [pledbrook/practical-groovy-public#3]
In section 2, the link:
   http://groovy-lang.org/docs/latest/html/groovy-jdk/
...results in a 404 and should instead be...
   http://**docs**.groovy-lang.org/docs/latest/html/groovy-jdk/

**Comment by pledbrook** [comment]
Thanks for the report. I'd fixed and parameterised all the other links, but missed that one.
